services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delayed-flights-api
    ports:
      - "5000:5000"
    networks:
      - app-net

  streamlit:
    build:
      context: .
      dockerfile: StreamlitDockerfile
    container_name: delayed-flights-ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - app-net
    environment:
      - API_URL=http://api:5000/predict

networks:
  app-net: