services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delayed-flights-api
    ports:
      - "5000:5000"
    networks:
      - app-net

  streamlit:
    build:
      context: .
      dockerfile: StreamlitDockerfile
    container_name: delayed-flights-ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - app-net
    environment:
      - API_URL=http://api:5000/predict
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.settimeout(2); s.connect(('localhost',8501))"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-net: