x-airflow-common:
  &airflow-common
  image: airflow-delayedflights:latest
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ../app:/opt/airflow/app
    - ../data:/opt/airflow/data
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    entrypoint: bash -c "airflow db init"
    depends_on:
      - postgres

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    <<: *airflow-common
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    <<: *airflow-common
    depends_on:
      - airflow-init
    command: scheduler

volumes:
  postgres-db-volume: